//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHangGoiMon
    {
        public int STT { get; set; }
        public string MaTk { get; set; }
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public float GiaTien { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TrangThai { get; set; }
        public float TongTien { get; set; }
        public System.DateTime TgGoiMon { get; set; }
        public Nullable<System.DateTime> TgGiao { get; set; }
    }
}
