//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.KHACHHANGTHUONGXUYENs = new HashSet<KHACHHANGTHUONGXUYEN>();
            this.KHACHHANGVANGLAIs = new HashSet<KHACHHANGVANGLAI>();
        }
    
        public string MaKH { get; set; }
        public string MaTK { get; set; }
        public string MaMay { get; set; }
        public string MaMayCu { get; set; }
        public Nullable<long> ThoiGianConLai { get; set; }
        public Nullable<float> TienGio { get; set; }
        public Nullable<long> TongThoiGian { get; set; }
    
        public virtual MAYTINH MAYTINH { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANGTHUONGXUYEN> KHACHHANGTHUONGXUYENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANGVANGLAI> KHACHHANGVANGLAIs { get; set; }
    }
}
