//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NETEntities : DbContext
    {
        public NETEntities()
            : base("name=NETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGLUONG> BANGLUONGs { get; set; }
        public virtual DbSet<CONGVIEC> CONGVIECs { get; set; }
        public virtual DbSet<GOIMON> GOIMONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHACHHANGTHUONGXUYEN> KHACHHANGTHUONGXUYENs { get; set; }
        public virtual DbSet<KHACHHANGVANGLAI> KHACHHANGVANGLAIs { get; set; }
        public virtual DbSet<MAYTINH> MAYTINHs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<QUANLYCONGVIEC> QUANLYCONGVIECs { get; set; }
        public virtual DbSet<QUANTRI> QUANTRIs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THUCDON> THUCDONs { get; set; }
        public virtual DbSet<TINNHAN> TINNHANs { get; set; }
        public virtual DbSet<KhachHangGoiMon> KhachHangGoiMons { get; set; }
        public virtual DbSet<view_BangLuong> view_BangLuong { get; set; }
        public virtual DbSet<view_CongViec> view_CongViec { get; set; }
        public virtual DbSet<view_GoiMon> view_GoiMon { get; set; }
        public virtual DbSet<view_KhachHang> view_KhachHang { get; set; }
        public virtual DbSet<view_KHTX> view_KHTX { get; set; }
        public virtual DbSet<view_KHVL> view_KHVL { get; set; }
        public virtual DbSet<view_MayTinh> view_MayTinh { get; set; }
        public virtual DbSet<view_NhanVien> view_NhanVien { get; set; }
        public virtual DbSet<view_QLCV> view_QLCV { get; set; }
        public virtual DbSet<view_QuanTri> view_QuanTri { get; set; }
        public virtual DbSet<view_TaiKhoan> view_TaiKhoan { get; set; }
        public virtual DbSet<view_ThucDon> view_ThucDon { get; set; }
        public virtual DbSet<view_UuDai> view_UuDai { get; set; }
    
        public virtual int sp_CapNhatMaMayChoKHACHHANG(string maKH, string maMay)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var maMayParameter = maMay != null ?
                new ObjectParameter("MaMay", maMay) :
                new ObjectParameter("MaMay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatMaMayChoKHACHHANG", maKHParameter, maMayParameter);
        }
    
        public virtual int sp_DangXuatTaiKhoan(string maTK)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("MaTK", maTK) :
                new ObjectParameter("MaTK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangXuatTaiKhoan", maTKParameter);
        }
    
        public virtual int sp_KhachHangDoiMatKhau(string maTK, string matkhaucu, string matkhaumoi)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("MaTK", maTK) :
                new ObjectParameter("MaTK", typeof(string));
    
            var matkhaucuParameter = matkhaucu != null ?
                new ObjectParameter("matkhaucu", matkhaucu) :
                new ObjectParameter("matkhaucu", typeof(string));
    
            var matkhaumoiParameter = matkhaumoi != null ?
                new ObjectParameter("matkhaumoi", matkhaumoi) :
                new ObjectParameter("matkhaumoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhachHangDoiMatKhau", maTKParameter, matkhaucuParameter, matkhaumoiParameter);
        }
    
        public virtual int sp_KhachHangGoiMon(string maTK, string maMon, Nullable<int> soluong)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("MaTK", maTK) :
                new ObjectParameter("MaTK", typeof(string));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("MaMon", maMon) :
                new ObjectParameter("MaMon", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhachHangGoiMon", maTKParameter, maMonParameter, soluongParameter);
        }
    
        public virtual ObjectResult<string> sp_Login(string taiKhoan, string matKhau)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("taiKhoan", taiKhoan) :
                new ObjectParameter("taiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Login", taiKhoanParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<sp_NhanVienLoad_Result> sp_NhanVienLoad(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NhanVienLoad_Result>("sp_NhanVienLoad", maNVParameter);
        }
    
        public virtual ObjectResult<sp_SearchNhanVien_Result> sp_SearchNhanVien(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchNhanVien_Result>("sp_SearchNhanVien", maNVParameter);
        }
    
        public virtual int sp_SuaBangLuong(string maLuong, string vaiTro, Nullable<float> luongTheoGio, string hinhThuc)
        {
            var maLuongParameter = maLuong != null ?
                new ObjectParameter("maLuong", maLuong) :
                new ObjectParameter("maLuong", typeof(string));
    
            var vaiTroParameter = vaiTro != null ?
                new ObjectParameter("vaiTro", vaiTro) :
                new ObjectParameter("vaiTro", typeof(string));
    
            var luongTheoGioParameter = luongTheoGio.HasValue ?
                new ObjectParameter("luongTheoGio", luongTheoGio) :
                new ObjectParameter("luongTheoGio", typeof(float));
    
            var hinhThucParameter = hinhThuc != null ?
                new ObjectParameter("hinhThuc", hinhThuc) :
                new ObjectParameter("hinhThuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaBangLuong", maLuongParameter, vaiTroParameter, luongTheoGioParameter, hinhThucParameter);
        }
    
        public virtual int sp_SuaCongViec(string maCV, string tenCV)
        {
            var maCVParameter = maCV != null ?
                new ObjectParameter("maCV", maCV) :
                new ObjectParameter("maCV", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("tenCV", tenCV) :
                new ObjectParameter("tenCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaCongViec", maCVParameter, tenCVParameter);
        }
    
        public virtual int sp_SuaGoiMon(Nullable<int> stt, string maTK, string maMon, Nullable<float> tongTien, Nullable<int> soLuong, string trangThai, Nullable<System.DateTime> tgGoiMon, Nullable<System.DateTime> tgGiao)
        {
            var sttParameter = stt.HasValue ?
                new ObjectParameter("stt", stt) :
                new ObjectParameter("stt", typeof(int));
    
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("tongTien", tongTien) :
                new ObjectParameter("tongTien", typeof(float));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(string));
    
            var tgGoiMonParameter = tgGoiMon.HasValue ?
                new ObjectParameter("tgGoiMon", tgGoiMon) :
                new ObjectParameter("tgGoiMon", typeof(System.DateTime));
    
            var tgGiaoParameter = tgGiao.HasValue ?
                new ObjectParameter("tgGiao", tgGiao) :
                new ObjectParameter("tgGiao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaGoiMon", sttParameter, maTKParameter, maMonParameter, tongTienParameter, soLuongParameter, trangThaiParameter, tgGoiMonParameter, tgGiaoParameter);
        }
    
        public virtual int sp_SuaKhachHang(string maKH, string maTK, string maMay, string maMayCu, Nullable<double> thoiGianConLai, Nullable<double> tienGio, Nullable<double> tongThoiGian)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            var maMayParameter = maMay != null ?
                new ObjectParameter("maMay", maMay) :
                new ObjectParameter("maMay", typeof(string));
    
            var maMayCuParameter = maMayCu != null ?
                new ObjectParameter("maMayCu", maMayCu) :
                new ObjectParameter("maMayCu", typeof(string));
    
            var thoiGianConLaiParameter = thoiGianConLai.HasValue ?
                new ObjectParameter("thoiGianConLai", thoiGianConLai) :
                new ObjectParameter("thoiGianConLai", typeof(double));
    
            var tienGioParameter = tienGio.HasValue ?
                new ObjectParameter("tienGio", tienGio) :
                new ObjectParameter("tienGio", typeof(double));
    
            var tongThoiGianParameter = tongThoiGian.HasValue ?
                new ObjectParameter("tongThoiGian", tongThoiGian) :
                new ObjectParameter("tongThoiGian", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaKhachHang", maKHParameter, maTKParameter, maMayParameter, maMayCuParameter, thoiGianConLaiParameter, tienGioParameter, tongThoiGianParameter);
        }
    
        public virtual int sp_SuaKHTX(Nullable<int> id, string maKH, string maUuDai, Nullable<double> soTienNap, string hoTen, Nullable<System.DateTime> ngaySinh, string sdt)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            var maUuDaiParameter = maUuDai != null ?
                new ObjectParameter("maUuDai", maUuDai) :
                new ObjectParameter("maUuDai", typeof(string));
    
            var soTienNapParameter = soTienNap.HasValue ?
                new ObjectParameter("soTienNap", soTienNap) :
                new ObjectParameter("soTienNap", typeof(double));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaKHTX", idParameter, maKHParameter, maUuDaiParameter, soTienNapParameter, hoTenParameter, ngaySinhParameter, sdtParameter);
        }
    
        public virtual int sp_SuaKHVL(Nullable<int> id, string maKH)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaKHVL", idParameter, maKHParameter);
        }
    
        public virtual int sp_SuaMayTinh(string maMay, string hang, string trangThai, Nullable<int> giaTien)
        {
            var maMayParameter = maMay != null ?
                new ObjectParameter("maMay", maMay) :
                new ObjectParameter("maMay", typeof(string));
    
            var hangParameter = hang != null ?
                new ObjectParameter("hang", hang) :
                new ObjectParameter("hang", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("giaTien", giaTien) :
                new ObjectParameter("giaTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaMayTinh", maMayParameter, hangParameter, trangThaiParameter, giaTienParameter);
        }
    
        public virtual int sp_SuaNhanVien(string maNV, string maLuong, string maCV, string maTk, string hoTen, Nullable<int> tuoi, string gioiTinh, string queQuan, string sdt, string trinhDoVH, string trinhDoHV, Nullable<int> soNamKN)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            var maLuongParameter = maLuong != null ?
                new ObjectParameter("maLuong", maLuong) :
                new ObjectParameter("maLuong", typeof(string));
    
            var maCVParameter = maCV != null ?
                new ObjectParameter("maCV", maCV) :
                new ObjectParameter("maCV", typeof(string));
    
            var maTkParameter = maTk != null ?
                new ObjectParameter("maTk", maTk) :
                new ObjectParameter("maTk", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var tuoiParameter = tuoi.HasValue ?
                new ObjectParameter("tuoi", tuoi) :
                new ObjectParameter("tuoi", typeof(int));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(string));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("queQuan", queQuan) :
                new ObjectParameter("queQuan", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var trinhDoVHParameter = trinhDoVH != null ?
                new ObjectParameter("trinhDoVH", trinhDoVH) :
                new ObjectParameter("trinhDoVH", typeof(string));
    
            var trinhDoHVParameter = trinhDoHV != null ?
                new ObjectParameter("trinhDoHV", trinhDoHV) :
                new ObjectParameter("trinhDoHV", typeof(string));
    
            var soNamKNParameter = soNamKN.HasValue ?
                new ObjectParameter("soNamKN", soNamKN) :
                new ObjectParameter("soNamKN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNhanVien", maNVParameter, maLuongParameter, maCVParameter, maTkParameter, hoTenParameter, tuoiParameter, gioiTinhParameter, queQuanParameter, sdtParameter, trinhDoVHParameter, trinhDoHVParameter, soNamKNParameter);
        }
    
        public virtual int sp_SuaQLCV(Nullable<int> id, string maNV, Nullable<System.DateTime> ngayLamViec, string caLamViec, Nullable<int> gioLamViec)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            var ngayLamViecParameter = ngayLamViec.HasValue ?
                new ObjectParameter("ngayLamViec", ngayLamViec) :
                new ObjectParameter("ngayLamViec", typeof(System.DateTime));
    
            var caLamViecParameter = caLamViec != null ?
                new ObjectParameter("caLamViec", caLamViec) :
                new ObjectParameter("caLamViec", typeof(string));
    
            var gioLamViecParameter = gioLamViec.HasValue ?
                new ObjectParameter("gioLamViec", gioLamViec) :
                new ObjectParameter("gioLamViec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaQLCV", idParameter, maNVParameter, ngayLamViecParameter, caLamViecParameter, gioLamViecParameter);
        }
    
        public virtual int sp_SuaQuanTri(string maQuanTri, string maTKAdmin, string maTKKhachHang, Nullable<System.DateTime> tgBatDau, Nullable<System.DateTime> tgKetThuc, string ghiChu)
        {
            var maQuanTriParameter = maQuanTri != null ?
                new ObjectParameter("maQuanTri", maQuanTri) :
                new ObjectParameter("maQuanTri", typeof(string));
    
            var maTKAdminParameter = maTKAdmin != null ?
                new ObjectParameter("maTKAdmin", maTKAdmin) :
                new ObjectParameter("maTKAdmin", typeof(string));
    
            var maTKKhachHangParameter = maTKKhachHang != null ?
                new ObjectParameter("maTKKhachHang", maTKKhachHang) :
                new ObjectParameter("maTKKhachHang", typeof(string));
    
            var tgBatDauParameter = tgBatDau.HasValue ?
                new ObjectParameter("tgBatDau", tgBatDau) :
                new ObjectParameter("tgBatDau", typeof(System.DateTime));
    
            var tgKetThucParameter = tgKetThuc.HasValue ?
                new ObjectParameter("tgKetThuc", tgKetThuc) :
                new ObjectParameter("tgKetThuc", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("ghiChu", ghiChu) :
                new ObjectParameter("ghiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaQuanTri", maQuanTriParameter, maTKAdminParameter, maTKKhachHangParameter, tgBatDauParameter, tgKetThucParameter, ghiChuParameter);
        }
    
        public virtual int sp_SuaTaiKhoan(string maTK, string taiKhoan, string matKhau, Nullable<System.DateTime> ngayTao, string tinhTrang)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("taiKhoan", taiKhoan) :
                new ObjectParameter("taiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("ngayTao", ngayTao) :
                new ObjectParameter("ngayTao", typeof(System.DateTime));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("tinhTrang", tinhTrang) :
                new ObjectParameter("tinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaTaiKhoan", maTKParameter, taiKhoanParameter, matKhauParameter, ngayTaoParameter, tinhTrangParameter);
        }
    
        public virtual int sp_SuaThucDon(string maMon, string tenMon, Nullable<float> tienNguyenLieu, Nullable<float> giaTien, Nullable<int> daBan, Nullable<int> conLai, string anh, string phanLoai)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("tenMon", tenMon) :
                new ObjectParameter("tenMon", typeof(string));
    
            var tienNguyenLieuParameter = tienNguyenLieu.HasValue ?
                new ObjectParameter("tienNguyenLieu", tienNguyenLieu) :
                new ObjectParameter("tienNguyenLieu", typeof(float));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("giaTien", giaTien) :
                new ObjectParameter("giaTien", typeof(float));
    
            var daBanParameter = daBan.HasValue ?
                new ObjectParameter("daBan", daBan) :
                new ObjectParameter("daBan", typeof(int));
    
            var conLaiParameter = conLai.HasValue ?
                new ObjectParameter("conLai", conLai) :
                new ObjectParameter("conLai", typeof(int));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(string));
    
            var phanLoaiParameter = phanLoai != null ?
                new ObjectParameter("PhanLoai", phanLoai) :
                new ObjectParameter("PhanLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaThucDon", maMonParameter, tenMonParameter, tienNguyenLieuParameter, giaTienParameter, daBanParameter, conLaiParameter, anhParameter, phanLoaiParameter);
        }
    
        public virtual int sp_SuaUuDai(string maUuDai, Nullable<float> phanTramTangThem, string ghiChu)
        {
            var maUuDaiParameter = maUuDai != null ?
                new ObjectParameter("maUuDai", maUuDai) :
                new ObjectParameter("maUuDai", typeof(string));
    
            var phanTramTangThemParameter = phanTramTangThem.HasValue ?
                new ObjectParameter("phanTramTangThem", phanTramTangThem) :
                new ObjectParameter("phanTramTangThem", typeof(float));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("ghiChu", ghiChu) :
                new ObjectParameter("ghiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaUuDai", maUuDaiParameter, phanTramTangThemParameter, ghiChuParameter);
        }
    
        public virtual int sp_ThemBangLuong(string maLuong, string vaiTro, Nullable<float> luongTheoGio, string hinhThuc)
        {
            var maLuongParameter = maLuong != null ?
                new ObjectParameter("maLuong", maLuong) :
                new ObjectParameter("maLuong", typeof(string));
    
            var vaiTroParameter = vaiTro != null ?
                new ObjectParameter("vaiTro", vaiTro) :
                new ObjectParameter("vaiTro", typeof(string));
    
            var luongTheoGioParameter = luongTheoGio.HasValue ?
                new ObjectParameter("luongTheoGio", luongTheoGio) :
                new ObjectParameter("luongTheoGio", typeof(float));
    
            var hinhThucParameter = hinhThuc != null ?
                new ObjectParameter("hinhThuc", hinhThuc) :
                new ObjectParameter("hinhThuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemBangLuong", maLuongParameter, vaiTroParameter, luongTheoGioParameter, hinhThucParameter);
        }
    
        public virtual int sp_ThemCongViec(string maCV, string tenCV)
        {
            var maCVParameter = maCV != null ?
                new ObjectParameter("maCV", maCV) :
                new ObjectParameter("maCV", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("tenCV", tenCV) :
                new ObjectParameter("tenCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCongViec", maCVParameter, tenCVParameter);
        }
    
        public virtual int sp_ThemGoiMon(string maTK, string maMon, Nullable<float> tongTien, Nullable<int> soLuong, string trangThai, Nullable<System.DateTime> tgGoiMon, Nullable<System.DateTime> tgGiao)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("tongTien", tongTien) :
                new ObjectParameter("tongTien", typeof(float));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(string));
    
            var tgGoiMonParameter = tgGoiMon.HasValue ?
                new ObjectParameter("tgGoiMon", tgGoiMon) :
                new ObjectParameter("tgGoiMon", typeof(System.DateTime));
    
            var tgGiaoParameter = tgGiao.HasValue ?
                new ObjectParameter("tgGiao", tgGiao) :
                new ObjectParameter("tgGiao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemGoiMon", maTKParameter, maMonParameter, tongTienParameter, soLuongParameter, trangThaiParameter, tgGoiMonParameter, tgGiaoParameter);
        }
    
        public virtual int sp_ThemKhachHang(string maKH, string maTK, string maMay, string maMayCu, Nullable<double> thoiGianConLai, Nullable<float> tienGio, Nullable<double> tongThoiGian)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            var maMayParameter = maMay != null ?
                new ObjectParameter("maMay", maMay) :
                new ObjectParameter("maMay", typeof(string));
    
            var maMayCuParameter = maMayCu != null ?
                new ObjectParameter("maMayCu", maMayCu) :
                new ObjectParameter("maMayCu", typeof(string));
    
            var thoiGianConLaiParameter = thoiGianConLai.HasValue ?
                new ObjectParameter("thoiGianConLai", thoiGianConLai) :
                new ObjectParameter("thoiGianConLai", typeof(double));
    
            var tienGioParameter = tienGio.HasValue ?
                new ObjectParameter("tienGio", tienGio) :
                new ObjectParameter("tienGio", typeof(float));
    
            var tongThoiGianParameter = tongThoiGian.HasValue ?
                new ObjectParameter("tongThoiGian", tongThoiGian) :
                new ObjectParameter("tongThoiGian", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhachHang", maKHParameter, maTKParameter, maMayParameter, maMayCuParameter, thoiGianConLaiParameter, tienGioParameter, tongThoiGianParameter);
        }
    
        public virtual int sp_ThemKHTX(string maKH, string maUuDai, Nullable<double> soTienNap, string hoTen, Nullable<System.DateTime> ngaySinh, string sdt)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            var maUuDaiParameter = maUuDai != null ?
                new ObjectParameter("maUuDai", maUuDai) :
                new ObjectParameter("maUuDai", typeof(string));
    
            var soTienNapParameter = soTienNap.HasValue ?
                new ObjectParameter("soTienNap", soTienNap) :
                new ObjectParameter("soTienNap", typeof(double));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKHTX", maKHParameter, maUuDaiParameter, soTienNapParameter, hoTenParameter, ngaySinhParameter, sdtParameter);
        }
    
        public virtual int sp_ThemKHVL(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKHVL", maKHParameter);
        }
    
        public virtual int sp_ThemMayTinh(string maMay, string hang, string trangThai, Nullable<int> giaTien)
        {
            var maMayParameter = maMay != null ?
                new ObjectParameter("maMay", maMay) :
                new ObjectParameter("maMay", typeof(string));
    
            var hangParameter = hang != null ?
                new ObjectParameter("hang", hang) :
                new ObjectParameter("hang", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("giaTien", giaTien) :
                new ObjectParameter("giaTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMayTinh", maMayParameter, hangParameter, trangThaiParameter, giaTienParameter);
        }
    
        public virtual int sp_ThemNhanVien(string maNV, string maLuong, string maCV, string maTk, string hoTen, Nullable<int> tuoi, string gioiTinh, string queQuan, string sdt, string trinhDoVH, string trinhDoHV, Nullable<int> soNamKN)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            var maLuongParameter = maLuong != null ?
                new ObjectParameter("maLuong", maLuong) :
                new ObjectParameter("maLuong", typeof(string));
    
            var maCVParameter = maCV != null ?
                new ObjectParameter("maCV", maCV) :
                new ObjectParameter("maCV", typeof(string));
    
            var maTkParameter = maTk != null ?
                new ObjectParameter("maTk", maTk) :
                new ObjectParameter("maTk", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var tuoiParameter = tuoi.HasValue ?
                new ObjectParameter("tuoi", tuoi) :
                new ObjectParameter("tuoi", typeof(int));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(string));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("queQuan", queQuan) :
                new ObjectParameter("queQuan", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var trinhDoVHParameter = trinhDoVH != null ?
                new ObjectParameter("trinhDoVH", trinhDoVH) :
                new ObjectParameter("trinhDoVH", typeof(string));
    
            var trinhDoHVParameter = trinhDoHV != null ?
                new ObjectParameter("trinhDoHV", trinhDoHV) :
                new ObjectParameter("trinhDoHV", typeof(string));
    
            var soNamKNParameter = soNamKN.HasValue ?
                new ObjectParameter("soNamKN", soNamKN) :
                new ObjectParameter("soNamKN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", maNVParameter, maLuongParameter, maCVParameter, maTkParameter, hoTenParameter, tuoiParameter, gioiTinhParameter, queQuanParameter, sdtParameter, trinhDoVHParameter, trinhDoHVParameter, soNamKNParameter);
        }
    
        public virtual int sp_ThemQLCV(string maNV, Nullable<System.DateTime> ngayLamViec, string caLamViec, Nullable<int> gioLamViec)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            var ngayLamViecParameter = ngayLamViec.HasValue ?
                new ObjectParameter("ngayLamViec", ngayLamViec) :
                new ObjectParameter("ngayLamViec", typeof(System.DateTime));
    
            var caLamViecParameter = caLamViec != null ?
                new ObjectParameter("caLamViec", caLamViec) :
                new ObjectParameter("caLamViec", typeof(string));
    
            var gioLamViecParameter = gioLamViec.HasValue ?
                new ObjectParameter("gioLamViec", gioLamViec) :
                new ObjectParameter("gioLamViec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemQLCV", maNVParameter, ngayLamViecParameter, caLamViecParameter, gioLamViecParameter);
        }
    
        public virtual int sp_ThemQuanTri(string maTKAdmin, string maTKKhachHang, Nullable<System.DateTime> tgBatDau, Nullable<System.DateTime> tgKetThuc, string ghiChu)
        {
            var maTKAdminParameter = maTKAdmin != null ?
                new ObjectParameter("maTKAdmin", maTKAdmin) :
                new ObjectParameter("maTKAdmin", typeof(string));
    
            var maTKKhachHangParameter = maTKKhachHang != null ?
                new ObjectParameter("maTKKhachHang", maTKKhachHang) :
                new ObjectParameter("maTKKhachHang", typeof(string));
    
            var tgBatDauParameter = tgBatDau.HasValue ?
                new ObjectParameter("tgBatDau", tgBatDau) :
                new ObjectParameter("tgBatDau", typeof(System.DateTime));
    
            var tgKetThucParameter = tgKetThuc.HasValue ?
                new ObjectParameter("tgKetThuc", tgKetThuc) :
                new ObjectParameter("tgKetThuc", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("ghiChu", ghiChu) :
                new ObjectParameter("ghiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemQuanTri", maTKAdminParameter, maTKKhachHangParameter, tgBatDauParameter, tgKetThucParameter, ghiChuParameter);
        }
    
        public virtual int sp_ThemTaiKhoan(string maTK, string taiKhoan, string matKhau, Nullable<System.DateTime> ngayTao, string tinhTrang)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("taiKhoan", taiKhoan) :
                new ObjectParameter("taiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("ngayTao", ngayTao) :
                new ObjectParameter("ngayTao", typeof(System.DateTime));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("tinhTrang", tinhTrang) :
                new ObjectParameter("tinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTaiKhoan", maTKParameter, taiKhoanParameter, matKhauParameter, ngayTaoParameter, tinhTrangParameter);
        }
    
        public virtual int sp_ThemThucDon(string maMon, string tenMon, Nullable<float> tienNguyenLieu, Nullable<float> giaTien, Nullable<int> daBan, Nullable<int> conLai, string anh, string phanLoai)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("tenMon", tenMon) :
                new ObjectParameter("tenMon", typeof(string));
    
            var tienNguyenLieuParameter = tienNguyenLieu.HasValue ?
                new ObjectParameter("tienNguyenLieu", tienNguyenLieu) :
                new ObjectParameter("tienNguyenLieu", typeof(float));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("giaTien", giaTien) :
                new ObjectParameter("giaTien", typeof(float));
    
            var daBanParameter = daBan.HasValue ?
                new ObjectParameter("daBan", daBan) :
                new ObjectParameter("daBan", typeof(int));
    
            var conLaiParameter = conLai.HasValue ?
                new ObjectParameter("conLai", conLai) :
                new ObjectParameter("conLai", typeof(int));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(string));
    
            var phanLoaiParameter = phanLoai != null ?
                new ObjectParameter("phanLoai", phanLoai) :
                new ObjectParameter("phanLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemThucDon", maMonParameter, tenMonParameter, tienNguyenLieuParameter, giaTienParameter, daBanParameter, conLaiParameter, anhParameter, phanLoaiParameter);
        }
    
        public virtual int sp_ThemUuDai(string maUuDai, Nullable<float> phanTramTangThem, string ghiChu)
        {
            var maUuDaiParameter = maUuDai != null ?
                new ObjectParameter("maUuDai", maUuDai) :
                new ObjectParameter("maUuDai", typeof(string));
    
            var phanTramTangThemParameter = phanTramTangThem.HasValue ?
                new ObjectParameter("phanTramTangThem", phanTramTangThem) :
                new ObjectParameter("phanTramTangThem", typeof(float));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("ghiChu", ghiChu) :
                new ObjectParameter("ghiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemUuDai", maUuDaiParameter, phanTramTangThemParameter, ghiChuParameter);
        }
    
        public virtual int sp_XoaBangLuong(string maLuong)
        {
            var maLuongParameter = maLuong != null ?
                new ObjectParameter("maLuong", maLuong) :
                new ObjectParameter("maLuong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaBangLuong", maLuongParameter);
        }
    
        public virtual int sp_XoaCongViec(string maCV)
        {
            var maCVParameter = maCV != null ?
                new ObjectParameter("maCV", maCV) :
                new ObjectParameter("maCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaCongViec", maCVParameter);
        }
    
        public virtual int sp_XoaGoiMon(Nullable<int> stt)
        {
            var sttParameter = stt.HasValue ?
                new ObjectParameter("stt", stt) :
                new ObjectParameter("stt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaGoiMon", sttParameter);
        }
    
        public virtual int sp_XoaKhachHang(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKhachHang", maKHParameter);
        }
    
        public virtual int sp_XoaKHTX(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKHTX", idParameter);
        }
    
        public virtual int sp_XoaKHVL(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKHVL", idParameter);
        }
    
        public virtual int sp_XoaMayTinh(string maMay)
        {
            var maMayParameter = maMay != null ?
                new ObjectParameter("maMay", maMay) :
                new ObjectParameter("maMay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaMayTinh", maMayParameter);
        }
    
        public virtual int sp_XoaNhanVien(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVien", maNVParameter);
        }
    
        public virtual int sp_XoaQLCV(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaQLCV", idParameter);
        }
    
        public virtual int sp_XoaQuanTri(string maQuanTri)
        {
            var maQuanTriParameter = maQuanTri != null ?
                new ObjectParameter("maQuanTri", maQuanTri) :
                new ObjectParameter("maQuanTri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaQuanTri", maQuanTriParameter);
        }
    
        public virtual int sp_XoaTaiKhoan(string maTK)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("maTK", maTK) :
                new ObjectParameter("maTK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaTaiKhoan", maTKParameter);
        }
    
        public virtual int sp_XoaThucDon(string maMon)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaThucDon", maMonParameter);
        }
    
        public virtual int sp_XoaUuDai(string maUuDai)
        {
            var maUuDaiParameter = maUuDai != null ?
                new ObjectParameter("maUuDai", maUuDai) :
                new ObjectParameter("maUuDai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaUuDai", maUuDaiParameter);
        }
    
        public virtual ObjectResult<ThongKeChiPhiDATU_Result> ThongKeChiPhiDATU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeChiPhiDATU_Result>("ThongKeChiPhiDATU");
        }
    
        public virtual ObjectResult<sp_HoatDongNhanVien_Result> sp_HoatDongNhanVien(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HoatDongNhanVien_Result>("sp_HoatDongNhanVien", maNVParameter);
        }
    
        public virtual ObjectResult<sp_LuongThangNhanVien_Result> sp_LuongThangNhanVien(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LuongThangNhanVien_Result>("sp_LuongThangNhanVien", maNVParameter);
        }
    
        public virtual ObjectResult<sp_LuongThangNhanVienAll_Result> sp_LuongThangNhanVienAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LuongThangNhanVienAll_Result>("sp_LuongThangNhanVienAll");
        }
    
        public virtual ObjectResult<ThongKeChiPhiDATU_Thang_Result> ThongKeChiPhiDATU_Thang(string thang)
        {
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeChiPhiDATU_Thang_Result>("ThongKeChiPhiDATU_Thang", thangParameter);
        }
    
        public virtual ObjectResult<ThongKeLuongThang_Result> ThongKeLuongThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeLuongThang_Result>("ThongKeLuongThang");
        }
    }
}
