//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANTRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUANTRI()
        {
            this.TINNHANs = new HashSet<TINNHAN>();
        }
    
        public int MaQuanTri { get; set; }
        public string MaTKAdmin { get; set; }
        public string MaTKKhachHang { get; set; }
        public System.DateTime TgBatDau { get; set; }
        public Nullable<System.DateTime> TgKetThuc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual TAIKHOAN TAIKHOAN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINNHAN> TINNHANs { get; set; }
    }
}
