//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINNHAN
    {
        public int Id { get; set; }
        public int MaQuanTri { get; set; }
        public string MaTKGui { get; set; }
        public string MaTKNhan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> TgGui { get; set; }
    
        public virtual QUANTRI QUANTRI { get; set; }
    }
}
