//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_TaiKhoan
    {
        public string MaTK { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string TinhTrang { get; set; }
    }
}
