//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_KhachHang
    {
        public string MaKH { get; set; }
        public string MaTK { get; set; }
        public string MaMay { get; set; }
        public string MaMayCu { get; set; }
        public Nullable<double> ThoiGianConLai { get; set; }
        public Nullable<float> TienGio { get; set; }
        public Nullable<double> TongThoiGian { get; set; }
    }
}
